name: C/C++ CI

on: [push, pull_request]

jobs:
  build_linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get glfw
      run: sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libglew-dev
    - name: build opengl2
      run: make -C demo/glfw_opengl2
    - name: build opengl3
      run: make -C demo/glfw_opengl3
    - name: build example
      run: make -C example

  build_msvc:
    env:
      vcpkgGitCommitId: 6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.arch }}-windows

    strategy:
      matrix:
        arch: [x86, x64]
        define: ['', '-DINCLUDE_ALL']
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
    - uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        vcpkgGitCommitId: ${{ env.vcpkgGitCommitId }}
        runVcpkgInstall: true
    - name: List ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }} after build
      run: find ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}
      shell: bash

    - name: Build gdi
      working-directory: demo/gdi
      run: ./build.bat ${{ matrix.define }}

    - name: Build gdip
      working-directory: demo/gdip
      run: ./build.bat ${{ matrix.define }}

    - name: Build gdi_native_nuklear
      working-directory: demo/gdi_native_nuklear
      run: ./build.bat ${{ matrix.define }}

    - name: Build d3d9
      working-directory: demo/d3d9
      run: ./build.bat ${{ matrix.define }}

    - name: Build d3d11
      working-directory: demo/d3d11
      run: ./build.bat ${{ matrix.define }}

    - name: Build d3d12
      working-directory: demo/d3d12
      run: ./build.bat ${{ matrix.define }}
